version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=coffebot
      - POSTGRES_PASSWORD=coffebot
      - POSTGRES_DB=coffebot_dev
  bot:
    build: .
    command: python manage.py bot
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:


  # web:
  #   build: .
  #   env_file:
  #     - ./.env.dev
  # web_migrate:
  #   extends:
  #     service: web
  #   command: python manage.py migrate
  # web_run:
  #   extends:
  #     service: web
  #   command: python manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - "8000:8000"
  # bot:
  #   extends:
  #     service: web
  #   command: python manage.py bot