# Generated by Django 4.0.1 on 2022-08-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Birthday', models.DateField(blank=True, null=True)),
                ('Phone_number', models.PositiveBigIntegerField(blank=True, default=0)),
                ('Addres', models.TextField(blank=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check', models.IntegerField(blank=True, default=1)),
                ('Cost', models.IntegerField(blank=True, default=0)),
                ('Paid', models.BooleanField(default=False)),
                ('Datetime', models.DateTimeField(auto_now=True)),
                ('Barista', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='cofbot.barista')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.PositiveIntegerField(unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Nomber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateRequest', models.DateField()),
                ('DateSupply', models.DateField()),
                ('Price', models.PositiveIntegerField()),
                ('Delivered', models.BooleanField()),
                ('Provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cofbot.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Count', models.PositiveIntegerField()),
                ('Ingred', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cofbot.ingredients')),
                ('Supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cofbot.supply')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count_ingred', models.IntegerField()),
                ('Ingred', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cofbot.ingredients')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cofbot.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.PositiveIntegerField(default=1)),
                ('Buying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cofbot.buying')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cofbot.product')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cofbot.profile')),
            ],
        ),
        migrations.AddField(
            model_name='buying',
            name='Customer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='cofbot.profile'),
        ),
    ]
